@host = http://localhost:3000/api/users
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMzY0MTQwNSwiZXhwIjoxNzAzNjg0NjA1fQ.Xiz80_Iho853oXsdzDDisrV9ILW6U-EO23sxDpDso90

### 권한 승급
PUT {{host}}/promote
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "targetEmail": "example2@example.com"
}